/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;
import java.net.*;
import java.io.*;

public class GreetServer implements Runnable {
    private ServerSocket serverSocket;
    private Socket clientSocket;
    private PrintWriter out;
    private BufferedReader in;

    public void start(int port) throws IOException {
        serverSocket = new ServerSocket(port);
        clientSocket = serverSocket.accept();
        out = new PrintWriter(clientSocket.getOutputStream(), true);
        in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));

        String echoMessage = in.readLine();

        out.println("(Echo) " + echoMessage);
        System.out.println("(Echo) " + echoMessage);
    }

    public void run() {
        try {
            System.out.println("Starting Server on port 6666");
            this.start(6666);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void stop() throws IOException {
        in.close();
        out.close();
        clientSocket.close();
        serverSocket.close();
    }
}
