/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class GreetClientTest {
    @Test
    public void givenGreetingClient_whenServerRespondsWhenStarted_thenCorrect() throws IOException {
        GreetClient client = new GreetClient();
        (new Thread(new GreetServer())).start();
        client.startConnection("127.0.0.1", 6666);
        String response = client.sendMessage("hello server");
        assertEquals("(Echo) hello server", response);

        client.stopConnection();
    }

//    @Test
//    public void givenGreetingClient_whenServerRespondsWhenUnrecognizedGreeting_thenRespond() throws IOException {
//        GreetClient client = new GreetClient();
//        (new Thread(new GreetServer())).start();
//        client.startConnection("127.0.0.1", 6666);
//        String response = client.sendMessage("This is not the message you are looking for");
//        assertEquals("unrecognised greeting", response);
//
//        client.stopConnection();
//    }
}
